using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using System.Text;
using System.IO;
using UnityEngine.Networking;
using System.Text.Json.Nodes;
using System.Linq;
using System.Text.RegularExpressions;
using System;

namespace Nekoyume
{
    public class OpenApiGenerator : EditorWindow
    {
        private const string _outputDir = "Assets/_Scripts/GeneratedApi";
        private const int _timeOut = 10;

        private static string _downloadJsonUrl;
        private static string _className;
        private static List<KeyValuePair<string, string>> _dataList = new List<KeyValuePair<string, string>>();
        private Vector2 _scrollPosition;

        [MenuItem("Tools/Generate OpenAPI Class")]
        private static void Init()
        {
            RefreshGeneratedInfo();
            var window = GetWindow(typeof(OpenApiGenerator));
            window.Show();
        }

        private void OnGUI()
        {
            RefreshGeneratedInfo();
            EditorGUILayout.BeginVertical();
            _scrollPosition = EditorGUILayout.BeginScrollView(_scrollPosition);
            _downloadJsonUrl = EditorGUILayout.TextField("DownloadJsonURL: ", _downloadJsonUrl);
            _className = EditorGUILayout.TextField("ClassName: ", _className);

            if (GUILayout.Button("Create"))
            {
                GenerateOpenApiClass(_downloadJsonUrl, _className);
            }

            GUILayout.Space(10);

            if (GUILayout.Button("RefreshAll"))
            {
                foreach (var item in _dataList)
                {
                    GenerateOpenApiClass(item.Value, item.Key);
                }
            }

            GUILayout.Space(10);

            if (_dataList != null)
            {
                GUILayout.BeginVertical();
                foreach (var data in _dataList)
                {
                    GUILayout.BeginHorizontal();
                    GUILayout.Label(new GUIContent(data.Key, data.Value));
                    if (GUILayout.Button("Apply"))
                    {
                        _className = data.Key;
                        _downloadJsonUrl = data.Value;
                    }
                    GUILayout.EndHorizontal();
                }
                GUILayout.EndVertical();
            }

            EditorGUILayout.EndScrollView();
            EditorGUILayout.EndVertical();
        }

        public static void GenerateOpenApiClass(string url, string className)
        {
            string apiUrl = url;

            string jsonSpec = DownloadOpenApiSpec(apiUrl);
            if (string.IsNullOrEmpty(jsonSpec))
            {
                UnityEngine.Debug.LogError("Failed to download OpenAPI spec.");
                return;
            }

            string generatedCode = GenerateCSharpFromOpenApiSpec(jsonSpec, className, url);
            if (string.IsNullOrEmpty(generatedCode))
            {
                UnityEngine.Debug.LogError("Failed to generate C# code from OpenAPI spec.");
                return;
            }

            if (!Directory.Exists(_outputDir))
            {
                Directory.CreateDirectory(_outputDir);
            }

            File.WriteAllText(Path.Combine(_outputDir, $"{className}.cs"), generatedCode);
            AssetDatabase.Refresh();
            RefreshGeneratedInfo();
        }

        private static string DownloadOpenApiSpec(string url)
        {
            using (var www = UnityWebRequest.Get(url))
            {
                www.SendWebRequest();
                while (!www.isDone) { }
                if (www.result != UnityWebRequest.Result.Success)
                {
                    UnityEngine.Debug.LogError("Failed to download: " + www.error);
                    return null;
                }
                return www.downloadHandler.text;
            }
        }

        private static string GenerateCSharpFromOpenApiSpec(string jsonSpec, string rootClassName, string url)
        {
            StringBuilder sb = new StringBuilder();
            JsonNode rootNode = JsonNode.Parse(jsonSpec);

            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by a tool.");
            sb.AppendLine("//     Do not modify the contents of this file directly.");
            sb.AppendLine("//     Changes might be overwritten the next time the code is generated.");
            sb.AppendLine("//     Source URL: " + url);
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");

            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using System.Net.Http;");

            sb.AppendLine();

            sb.AppendLine($"public class {rootClassName}");
            sb.AppendLine("{");
            sb.AppendLine("    private string Url;");
            sb.AppendLine("    private readonly HttpClient _client;");
            sb.AppendLine();
            sb.AppendLine($"    public {rootClassName}(string url)");
            sb.AppendLine("    {");
            sb.AppendLine($"        Url = url;");
            sb.AppendLine("        _client = new System.Net.Http.HttpClient();");
            sb.AppendLine($"        _client.Timeout = TimeSpan.FromSeconds({_timeOut});");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public void Dispose()");
            sb.AppendLine("    {");
            sb.AppendLine("        _client.Dispose();");
            sb.AppendLine("    }");

            if (rootNode["components"]?["schemas"] is JsonObject schemas)
            {
                foreach (var schema in schemas)
                {
                    string className = schema.Key;

                    if (schema.Value["enum"] is JsonArray enumValues)
                    {
                        sb.AppendLine($"    [JsonConverter(typeof({schema.Key}TypeConverter))]");
                        sb.AppendLine($"    public enum {schema.Key}");
                        sb.AppendLine("    {");

                        string description = schema.Value["description"] != null ? schema.Value["description"].ToString() : string.Empty;
                        Dictionary<string, string> enumMapping = new Dictionary<string, string>();

                        var enumType = schema.Value["type"]?.ToString();

                        if (enumType != "string")
                        {
                            foreach (var line in description.Split('\n'))
                            {
                                if (line.Contains(":"))
                                {
                                    var parts = line.Trim().Split(':');
                                    if (parts.Length == 2)
                                    {
                                        var name = parts[1];
                                        string pattern = "`(.*?)`";
                                        Match match = Regex.Match(name, pattern);
                                        if (match.Success)
                                        {
                                            name = match.Groups[0].Value.Trim('`');
                                        }
                                        enumMapping[parts[0].Trim('*').Trim().Replace("- **", string.Empty).TrimEnd('\"')] = name;
                                    }
                                }
                            }
                        }
                        string preText = string.Empty;
                        for (int i = 0; i < enumValues.Count; i++)
                        {
                            var enumVal = enumValues[i].ToString();
                            if (enumMapping.ContainsKey(enumVal))
                            {
                                string enumName = enumMapping[enumVal];

                                if (enumName == enumVal)
                                {
                                    if (int.TryParse(enumName[0].ToString(), out var number))
                                    {
                                        sb.AppendLine($"        _{enumName},");
                                        preText = "\"_\"+";
                                    }
                                    else
                                    {
                                        sb.AppendLine($"        {enumName},");
                                    }
                                }
                                else
                                {
                                    if (int.TryParse(enumName[0].ToString(), out var number))
                                    {
                                        if (int.TryParse(enumVal[0].ToString(), out var enumValNumber))
                                        {
                                            sb.AppendLine($"        _{enumName} = {enumVal},");
                                            preText = "\"_\"+";
                                        }
                                        else
                                        {
                                            sb.AppendLine($"        _{enumVal},");
                                            preText = "\"_\"+";
                                        }
                                    }
                                    else
                                    {
                                        sb.AppendLine($"        {enumName} = {enumVal},");
                                    }
                                }
                            }
                            else
                            {

                                if (int.TryParse(enumVal[0].ToString(), out var number))
                                {
                                    sb.AppendLine($"        _{enumVal},");
                                    preText = "\"_\"+";
                                }
                                else
                                {
                                    sb.AppendLine($"        {enumVal},");
                                }
                            }
                        }

                        sb.AppendLine("    }");
                        sb.AppendLine();

                        sb.AppendLine($"    public class {schema.Key}TypeConverter : JsonConverter<{schema.Key}>");
                        sb.AppendLine("    {");
                        sb.AppendLine("        public override " + schema.Key + " Read(");
                        sb.AppendLine("            ref Utf8JsonReader reader,");
                        sb.AppendLine("            Type typeToConvert,");
                        sb.AppendLine("            JsonSerializerOptions options)");
                        sb.AppendLine("        {");
                        sb.AppendLine("            return reader.TokenType switch");
                        sb.AppendLine("            {");
                        sb.AppendLine("                JsonTokenType.Number => (" + schema.Key + ")reader.GetInt32(),");
                        sb.AppendLine("                JsonTokenType.String => Enum.Parse<" + schema.Key + ">(" + preText + "reader.GetString()),");
                        sb.AppendLine("                _ => throw new JsonException(");
                        sb.AppendLine("                    $\"Expected token type to be {string.Join(\" or \", new[] { JsonTokenType.Number, JsonTokenType.String })} but got {reader.TokenType}\")");
                        sb.AppendLine("            };");
                        sb.AppendLine("        }");

                        sb.AppendLine("        public override void Write(");
                        sb.AppendLine("            Utf8JsonWriter writer,");
                        sb.AppendLine($"            {schema.Key} value,");
                        sb.AppendLine("            JsonSerializerOptions options)");
                        sb.AppendLine("        {");
                        sb.AppendLine("            writer.WriteNumberValue((int)value);");
                        sb.AppendLine("        }");
                        sb.AppendLine("    }");
                        sb.AppendLine();

                        continue;
                    }

                    sb.AppendLine($"    public class {className}");
                    sb.AppendLine("    {");

                    if (schema.Value["properties"] is JsonObject properties)
                    {
                        foreach (var property in properties)
                        {
                            string propName = property.Key;
                            string propType = ConvertToCSharpType(property.Value);

                            if (property.Value["type"]?.ToString() == "array")
                            {
                                propType = $"List<{ConvertToCSharpType(property.Value["items"])}>";
                            }

                            var splited = propName.Split("_");
                            for (int i = 0; i < splited.Length; i++)
                            {
                                splited[i] = char.ToUpper(splited[i][0]) + splited[i].Substring(1);
                            }
                            string formattedPropName = string.Concat(splited);
                            sb.AppendLine($"        [JsonPropertyName(\"{propName}\")]");
                            sb.AppendLine($"        public {propType} {formattedPropName} {{ get; set; }}");
                        }
                    }

                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
            }

            var paths = rootNode["paths"];
            AppendWebRequestsFromPaths(sb, paths);
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string ConvertToCSharpType(JsonNode jsonNode)
        {
            string jsonType = string.Empty;
            if (jsonNode["type"] != null)
            {
                jsonType = jsonNode["type"].ToString();
            }
            else if (jsonNode["$ref"] != null)
            {
                var splited = jsonNode["$ref"]?.ToString().Split("/");
                return splited[splited.Length - 1];
            }
            else if (jsonNode["anyOf"] != null)
            {
                return ConvertToCSharpType(jsonNode["anyOf"][0]) + "?";
            }
            switch (jsonType)
            {
                case "string": return "string";
                case "integer": return "int";
                case "boolean": return "bool";
                case "number": return "decimal";

                default: return "object";
            }
        }

        private static void AppendWebRequestsFromPaths(StringBuilder sb, JsonNode pathsNode)
        {
            foreach (var pathItem in pathsNode as JsonObject)
            {
                string path = pathItem.Key;
                if (!path.Contains("api"))
                    continue;

                if (pathItem.Value is JsonObject methods)
                {
                    foreach (var method in methods)
                    {
                        string httpMethod = method.Key.ToUpper();

                        string methodName = GenerateMethodNameFromPathAndMethod(path, httpMethod);
                        string returnType = "string";

                        StringBuilder parameterDefinitions = new StringBuilder();
                        StringBuilder parameterUsages = new StringBuilder();

                        var parameters = method.Value["parameters"];
                        if (parameters != null)
                        {
                            foreach (var parameter in parameters as JsonArray)
                            {
                                string parameterName = parameter["name"].ToString();
                                string parameterType = ConvertToCSharpType(parameter["schema"]);

                                parameterDefinitions.Append($"{parameterType} {parameterName}, ");
                                if (parameter["in"].ToString() == "query")
                                {
                                    parameterUsages.AppendLine($"            url += \"?{parameterName}=\" + {parameterName}.ToString();");
                                }
                            }
                            parameterUsages.AppendLine("            request.RequestUri = new Uri(url);");
                        }

                        var requestBody = method.Value["requestBody"];
                        if (requestBody != null)
                        {
                            string requestBodyType = "string";
                            if (requestBody["content"]["application/json"]["schema"]["$ref"] != null)
                            {
                                string schemaRef = requestBody["content"]["application/json"]["schema"]["$ref"].ToString();
                                string[] parts = schemaRef.Split('/');
                                requestBodyType = parts[parts.Length - 1];
                            }

                            parameterDefinitions.Append($"{requestBodyType} requestBody, ");
                            parameterUsages.AppendLine($"            request.Content = new System.Net.Http.StringContent(System.Text.Json.JsonSerializer.Serialize(requestBody), System.Text.Encoding.UTF8, \"application/json\");");
                        }

                        bool hasReturnType = false;
                        var responseSchema = method.Value["responses"]?["200"]?["content"]?["application/json"]?["schema"];
                        if (responseSchema != null)
                        {
                            if (responseSchema["$ref"] != null)
                            {
                                string schemaRef = responseSchema["$ref"].ToString();
                                string[] parts = schemaRef.Split('/');
                                returnType = parts[parts.Length - 1];
                                hasReturnType = true;
                            }

                            if (responseSchema["type"] != null &&
                                responseSchema["type"].ToString() == "array" &&
                                responseSchema["items"] != null)
                            {
                                string schemaRef;

                                if (responseSchema["items"]["$ref"] != null)
                                {
                                    schemaRef = responseSchema["items"]["$ref"].ToString();
                                    string[] parts = schemaRef.Split('/');
                                    returnType = parts[parts.Length - 1] + "[]";
                                }

                                if (responseSchema["items"]["type"] != null)
                                {
                                    schemaRef = responseSchema["items"]["type"].ToString();
                                    returnType = schemaRef + "[]";
                                }
                                hasReturnType = true;
                            }
                        }

                        sb.AppendLine($"    public async Task {methodName}({parameterDefinitions}Action<{returnType}> onSuccess, Action<string> onError)");
                        sb.AppendLine("    {");
                        sb.AppendLine($"        string url = Url + \"{path}\";");
                        sb.AppendLine($"        using (var request = new System.Net.Http.HttpRequestMessage(new System.Net.Http.HttpMethod(\"{httpMethod}\"), url))");
                        sb.AppendLine("        {");
                        sb.Append(parameterUsages);
                        sb.AppendLine("            try");
                        sb.AppendLine("            {");
                        sb.AppendLine("                var response = await _client.SendAsync(request);");
                        sb.AppendLine("                response.EnsureSuccessStatusCode();");
                        sb.AppendLine("                var responseBody = await response.Content.ReadAsStringAsync();");
                        if (hasReturnType)
                        {
                            sb.AppendLine($"                {returnType} result = System.Text.Json.JsonSerializer.Deserialize<{returnType}>(responseBody);");
                            sb.AppendLine("                onSuccess?.Invoke(result);");
                        }
                        else
                        {
                            sb.AppendLine("                onSuccess?.Invoke(responseBody);");
                        }
                        sb.AppendLine("            }");
                        sb.AppendLine("            catch (Exception ex)");
                        sb.AppendLine("            {");
                        sb.AppendLine("                onError?.Invoke(ex.Message);");
                        sb.AppendLine("            }");
                        sb.AppendLine("        }");
                        sb.AppendLine("    }");
                        sb.AppendLine();
                    }
                }
            }
        }

        private static string GenerateMethodNameFromPathAndMethod(string path, string httpMethod)
        {
            StringBuilder sb = new StringBuilder();
            var methodName = httpMethod.ToLower();
            methodName = char.ToUpper(methodName[0]) + methodName.Substring(1);
            sb.Append(methodName);
            string[] segments = path.Split('/');
            foreach (var segment in segments)
            {
                if (!string.IsNullOrEmpty(segment))
                {
                    sb.Append(char.ToUpper(segment[0]) + segment.Substring(1));
                }
            }
            return sb.ToString().Replace("-", "").Replace("Api", string.Empty) + "Async";
        }

        private static void RefreshGeneratedInfo()
        {
            if (Directory.Exists(_outputDir))
            {
                string[] filePaths = Directory.GetFiles(_outputDir, "*.cs", SearchOption.AllDirectories);
                if (filePaths.Length == _dataList.Count)
                    return;
                _dataList.Clear();
                foreach (var filePath in filePaths)
                {
                    string content = File.ReadAllText(filePath);
                    string pattern = @"//     Source URL: \S+";
                    Match match = Regex.Match(content, pattern);
                    if (match.Success)
                    {
                        var fileName = Path.GetFileNameWithoutExtension(filePath);
                        var sourceUrl = match.Value.Replace("//     Source URL: ", string.Empty);
                        _dataList.Add(new KeyValuePair<string, string>(fileName, sourceUrl));
                    }
                    else
                    {
                        continue;
                    }
                }
            }
        }
    }
}
