#!/bin/sh
set -e

cd Lib9c/
if command -v dotnet > /dev/null; then
  dotnet build -v q
elif command -v msbuild > /dev/null; then
  msbuild /r /v:q
else
  echo "You need .NET Core SDK or Mono SDK or Visual Studio." > /dev/stderr
  exit 1
fi
cd ..
