#!/usr/bin/env bash

INSTALL_DIR="$2"
UPDATER="$INSTALL_DIR/Nine Chronicles Updater"
FILE_OWNER="$(stat -f '%Su' "$UPDATER")"

"$UPDATER"
SNAPSHOT_PATH="/Users/$FILE_OWNER/.local/share/planetarium/9c"
chown -R "$FILE_OWNER" "$SNAPSHOT_PATH"
