namespace Nekoyume.Action
{
    public enum ShopErrorType
    {
        ERROR_CODE_FAILED_LOADING_STATE = 1,
        ERROR_CODE_ITEM_DOES_NOT_EXIST = 2,
        ERROR_CODE_SHOPITEM_EXPIRED = 3,
        ERROR_CODE_INSUFFICIENT_BALANCE = 4,
        ERROR_CODE_INVALID_ADDRESS = 5,
        ERROR_CODE_INVALID_PRICE = 6,
        ERROR_CODE_INVALID_ORDERID = 7,
        ERROR_CODE_INVALID_TRADABLEID = 8,
        ERROR_CODE_INVALID_ITEMTYPE = 9,
        ERROR_CODE_DUPLICATE_SELL = 10
    }
}